# Generated by Django 3.0.2 on 2020-02-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200210_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='thumb',
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='articlesPictures'),
        ),
    ]
