# Generated by Django 3.0.2 on 2020-02-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
