# Generated by Django 3.0.2 on 2020-02-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='imageSmall',
            field=models.ImageField(blank=True, default='default.png', upload_to='articlesPictures/articlesSmall'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='articlesPictures/articlesImages'),
        ),
    ]
