# Generated by Django 3.0.2 on 2020-02-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200217_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='defaultImage.jpg', upload_to='articlesPictures/articlesImages'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='imageSmall',
            field=models.ImageField(blank=True, default='defaultImageSmall.png', upload_to='articlesPictures/articlesSmall'),
        ),
    ]
